### ISSUE TITLE
Gas Estimate

### ISSUE THREAD

**Issue by elrazez** [Minh-Trng/dex-buy-tools#5]
hey, i'm trying to swap on avax and it was working before this but now i get a weird gas estimate and this:

```
Transaction not executed, because the gas estimate is greater than the limit configured in the buy_params-file.
Gas estimate in wei : 163852000000000000
Traceback (most recent call last):
  File "/usr/local/bin/dexbuy", line 8, in <module>
    sys.exit(dexbuy())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/__main__.py", line 36, in instant
    helper.buy_instantly(token_address)
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/AvaxHelper.py", line 27, in buy_instantly
    super().perform_uniswapv2_style_buy(self.dex_router, token_address,
  File "/usr/local/lib/python3.9/site-packages/dexbuytools/helpers/EvmBaseHelper.py", line 71, in perform_uniswapv2_style_buy
    raise NotImplementedError
NotImplementedError
```

would appericate it of you could tell me how to fix this. i tried using fixed gas in `EvmBaseHelper.py` but i get the error that it's less than base fee per block.

**Comment by Minh-Trng** [comment]
"MAX_GAS_ESTIMATE: 0.1" is the value of AVAX that you are willing to pay as gas. if the network estimates that the tx might be more expensive, than this project wont execute the tx

**Comment by elrazez** [comment]
I know but look at the wei amount of gas in the error. that's like more than 2000 AVAX!

**Comment by Minh-Trng** [comment]
nah that gas estimate is roughly 0.16 avax

**Comment by elrazez** [comment]
aaaahh there was a bug in my gas calculator that i wrote! thanks again.
